allowBuilds:
  "@heroui/shared-utils": true
  "@parcel/watcher": true
  "@swc/core": true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.2'
  - '@yusifaliyevpro/countries@5.0.0'
